# Generated by Django 3.0.8 on 2021-01-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('latitude', models.CharField(blank=True, max_length=200, null=True)),
                ('longitude', models.CharField(blank=True, max_length=200, null=True)),
                ('fillColor', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('c_radius', models.CharField(blank=True, max_length=200, null=True)),
                ('c_lat', models.CharField(blank=True, max_length=200, null=True)),
                ('c_lng', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lat1', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lng1', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lat2', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lng2', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lat3', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lng3', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lat4', models.CharField(blank=True, max_length=200, null=True)),
                ('r_lng4', models.CharField(blank=True, max_length=200, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
