# Generated by Django 3.0.8 on 2021-01-08 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblVehicleData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_status', models.CharField(choices=[('Moving', 'Moving'), ('Idle', 'Idle'), ('Parking', 'Parking')], max_length=100)),
                ('speed', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField(auto_now=True, null=True)),
                ('current_location', models.CharField(max_length=500)),
                ('end_point', models.CharField(max_length=500)),
                ('icon', models.CharField(choices=[('Rikshaw', 'Rikshaw'), ('Car', 'Car'), ('Scooter', 'Scooter'), ('Truck', 'Truck'), ('Bike', 'Bike'), ('LargeTruck', 'LargeTruck')], default='Truck', max_length=100)),
                ('icon_marker', models.CharField(choices=[('RikshawMarker', 'RikshawMarker'), ('CarMarker', 'CarMarker'), ('ScooterMarker', 'ScooterMarker'), ('TruckMarker', 'TruckMarker'), ('BikeMarker', 'BikeMarker'), ('LargeTruckMarker', 'LargeTruckMarker')], default='TruckMarker', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tblCoordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('vehicle_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position', to='locationTracking.tblVehicleData')),
            ],
        ),
    ]
