# Generated by Django 3.1.7 on 2021-02-27 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='endpoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startpoint',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
